# Generated by Django 6.0.2 on 2026-02-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills_required',
            new_name='skills',
        ),
    ]
