services:
  db:
    image: postgres:15
    container_name: expense_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: expense_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/expense_db
      SECRET_KEY: super-secret-key
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
